# Generated by WhyDenied. Review before merging.
#
# arn:aws:iam::734143849862:role/orders-api-role
# was denied ssm:GetParametersByPath
# on arn:aws:ssm:us-east-1:734143849862:parameter/demo/orders-api
# because no identity-based policy allowed it.
# First seen 2026-09-20T06:35:48Z.

resource "aws_iam_role_policy" "whydenied_ssm_getparametersbypath_2ebafa" {
  name = "whydenied_ssm_getparametersbypath_2ebafa"
  role = aws_iam_role.orders_api.name

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect   = "Allow"
      Action   = "ssm:GetParametersByPath"
      Resource = "arn:aws:ssm:us-east-1:734143849862:parameter/demo/orders-api"
    }]
  })
}
